version: "3"

services:
  backend:
    build: ./backend
    container_name: ship-router-backend
    volumes:
      # provide the path to your own coastline file here
      # your file will be mounted to `/data.pbf`
      - ./backend/data/planet-coastlines.pbf:/data.pbf
    environment:
      - PORT=9090
      - DATAFILE=/data.pbf
      - NUMBER_OF_SPHERE_NODES=1000
    ports:
      - "9090:9090"

  frontend:
    build: ./frontend
    container_name: ship-router-frontend
    ports:
      - "8080:8080"
